version: "3"

# Get your authtoken at https://dashboard.ngrok.com/authtokens
# Get your free static domain at https://dashboard.ngrok.com/domains
agent:
  authtoken: "{{NGROK_AUTH_TOKEN}}"
tunnels:
  beckn:
    proto: http
    addr: 9000
    domain: "{{NGROK_DEV_DOMAIN}}"