services:
  redis-cnode:
    image: redis:alpine
    container_name: redis-cnode
    networks:
      - beckn_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  onix-bap:
    image: fidedocker/onix-adapter:latest
    container_name: onix-bap
    platform: linux/amd64
    networks:
      - beckn_network
    ports:
      - "8081:8081"
    environment:
      CONFIG_FILE: "/app/config/local-simple-bap.yaml"
      OTEL_EXPORTER_OTLP_INSECURE: true
    volumes:
      - ./config:/app/config
    command: [ "./server", "--config=/app/config/local-simple-bap.yaml" ]

  otel-collector-bap:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector-bap
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./config/otel-collector-bap/config.yaml:/etc/otel/config.yaml:ro
    networks:
      - beckn_network
    restart: unless-stopped

networks:
  beckn_network:
    name: beckn_network
    driver: bridge
