routingRules:
  - version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - select
      - init
      - confirm
      - status
      - track
      - update
      - cancel
      - rate
      - support
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "https://discover.infra.ion.id/beckn"
    endpoints:
      - discover
